"""log tables

Revision ID: c3a0b72feff1
Revises: a14e8e37b0dc
Create Date: 2025-04-25 01:04:29.540777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a0b72feff1'
down_revision: Union[str, None] = 'a14e8e37b0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('tasks_update', 'tasks_post', 'tasks_delete', name='entityenum'), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
